"""add_round_table_tables_updated

Revision ID: 85131176a608
Revises: 2885bbe13275
Create Date: 2025-01-04 14:08:29.335323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85131176a608'
down_revision: Union[str, None] = '2885bbe13275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round_tables', sa.Column('title', sa.String(), nullable=False))
    op.add_column('round_tables', sa.Column('context', sa.String(), nullable=True))
    op.drop_column('round_tables', 'objective')
    op.drop_column('round_tables', 'current_phase')
    op.drop_column('round_tables', 'max_rounds')
    op.drop_column('round_tables', 'phase_config')
    op.drop_column('round_tables', 'name')
    op.drop_column('round_tables', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round_tables', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('round_tables', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('round_tables', sa.Column('phase_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('round_tables', sa.Column('max_rounds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('round_tables', sa.Column('current_phase', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('round_tables', sa.Column('objective', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('round_tables', 'context')
    op.drop_column('round_tables', 'title')
    # ### end Alembic commands ###
